update

diff --git a/tech-tutorials/github-action/slack-notification/slack-notification-example.yml b/tech-tutorials/github-action/slack-notification/slack-notification-example.yml
--- a/tech-tutorials/github-action/slack-notification/slack-notification-example.yml
+++ b/tech-tutorials/github-action/slack-notification/slack-notification-example.yml
@@ -1,10 +1,13 @@
 name: Slack Notification Example
 
 on:
-  # pull_request:
+  # pull_request: 
   #   types:
   #     - opened
-
+  #     - edited
+  push:
+    branches:
+      - main
   workflow_dispatch:
     inputs:
       environment:
@@ -15,8 +18,8 @@ on:
           - test
 
 env:
-  SLACK_CHANNEL_ID: Your Slack Id
-  SLACK_ENV_NAME: Your Env Name
+  SLACK_CHANNEL_ID: Your Slack Channel ID
+  SLACK_ENV_NAME: TEST
   SLACK_REPO_NAME: devto-code-snippets
   PIPELINE_URL: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
   PR_URL: 'https://github.com/${{ github.repository }}/pull/'
@@ -57,11 +60,22 @@ jobs:
           echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
           echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
 
+
+      - name: Check if SLACK_BOT_TOKEN is present
+        run: |
+            if [ -z "${{ secrets.SLACK_BOT_TOKEN }}" ]; then
+            echo "SLACK_BOT_TOKEN is missing!"
+            exit 1
+            else
+            echo "SLACK_BOT_TOKEN is set."
+            fi
+
+
       - name: Notify start on Slack
         id: notify
         uses: slackapi/slack-github-action@v2.0.0
         with:
-          token: ${{ secrets.SLACK_TOKEN }}
+          token: ${{ secrets.SLACK_BOT_TOKEN }}
           method: chat.postMessage
           payload: |
             channel: ${{ env.SLACK_CHANNEL_ID }}
@@ -115,7 +129,7 @@ jobs:
       - name: Notify end on Slack
         uses: slackapi/slack-github-action@v2.0.0
         with:
-          token: ${{ secrets.SLACK_BOT }}
+          token: ${{ secrets.SLACK_BOT_TOKEN }}
           method: chat.update
           payload: |
             channel: ${{ env.SLACK_CHANNEL_ID }}
