Update slack-notification-example.yml

diff --git a/.github/workflows/slack-notification-example.yml b/.github/workflows/slack-notification-example.yml
--- a/.github/workflows/slack-notification-example.yml
+++ b/.github/workflows/slack-notification-example.yml
@@ -56,11 +56,21 @@ jobs:
           echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
           echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
 
+      - name: Check if SLACK_BOT_TOKEN is present
+        run: |
+            if [ -z "${{ secrets.SLACK_BOT_TOKEN }}" ]; then
+            echo "SLACK_BOT_TOKEN is missing!"
+            exit 1
+            else
+            echo "SLACK_BOT_TOKEN is set."
+            fi
+
+
       - name: Notify start on Slack
         id: notify
         uses: slackapi/slack-github-action@v2.0.0
         with:
-          token: ${{ secrets.SLACK_TOKEN }}
+          token: ${{ secrets.SLACK_BOT_TOKEN }}
           method: chat.postMessage
           payload: |
             channel: ${{ env.SLACK_CHANNEL_ID }}
@@ -114,7 +124,7 @@ jobs:
       - name: Notify end on Slack
         uses: slackapi/slack-github-action@v2.0.0
         with:
-          token: ${{ secrets.SLACK_BOT }}
+          token: ${{ secrets.SLACK_BOT_TOKEN }}
           method: chat.update
           payload: |
             channel: ${{ env.SLACK_CHANNEL_ID }}
